# Generated by Django 2.0.6 on 2018-07-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('book_title', models.TextField(default='')),
                ('reader_name', models.TextField(default='')),
                ('location_name_or_address', models.TextField(default='')),
                ('reason', models.TextField(default='')),
                ('fun_fact', models.TextField(default='')),
                ('image_url', models.URLField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('marker_label', models.TextField(default='')),
            ],
        ),
    ]
