# Generated by Django 2.0.6 on 2018-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180701_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
