# Generated by Django 2.0.6 on 2018-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_reading_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
