# Generated by Django 2.0.6 on 2018-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_reading_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='synopsis_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='reading',
            name='author',
            field=models.CharField(default='No Author Added', max_length=200),
        ),
    ]
