# Generated by Django 2.0.6 on 2018-07-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_reading_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='email_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='phone_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
